name: Manual workflow
'on':
  workflow_dispatch:
    inputs:
      environment:
        description: environment
        default: qa
        required: true
        type: choice
        options:
          - dev
          - acceptance
          - perf
          - stage
          - local
          - qa
      tags:
        description: tags
        required: false
        type: choice
        options:
          - smoke
          - Regression
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - run: |
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          TAGS: '${{ inputs.tags }}'
          ENVIRONMENT: '${{ inputs.environment }}'
      - name: Run tests
        run: mvn test  "-DenvTarget=${{ inputs.environment }}" "-Dcucumber.options='--tags ${{ inputs.tags }}"
      - name: Archive Cucumber Reports
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-reports
          path: target/cucumber-html-report
      - name: Cucumber-html-report
        uses: mt185252/cucumber-html-report-generator@v1
        with:
          report-theme: hierarchy
          json-file-path: '${{ github.workspace}}/target/cucumber.json'
          report-metadata: '{"Date":"05-May-2024", "Time":"23:30 IST", "Environment": {{ inputs.environment }}}'
      - name: Upload HTML report as an artifact to GitHub
        id: artifact_upload
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: '${{ github.workspace }}/target/cucumber_03_05_2024_T15_10_19.html'
          if-no-files-found: error
          retention-days: 90
