# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment: 
        # Friendly description to be shown in the UI instead of 'name'
        description: 'environment'
        # Default value if no value is explicitly provided
        default: 'qa'          
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: choice
        options:
        - dev
        - acceptance
        - perf
        - stage
        - local
        - qa
      tags:
        description: 'tags'
        required: false
        type: choice
        options:
        - smoke
        - Regression
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: |
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
      env:
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
    - name: Run tests
      run: mvn test  "-DenvTarget=${{ inputs.environment }}" "-Dcucumber.options='--tags ${{ inputs.tags }}''--plugin json:target/cucumber-report.json,html:target/cucumber-html-report'"

    - name: Archive Cucumber Reports
      uses: actions/upload-artifact@v2
      with:
       name: cucumber-reports
       path: target/cucumber-html-reports
    - name: Cucumber HTML Report Generator
      run: |
          npm install cucumber-html-reporter
          npx cucumber-html-reporter --json-file target/report.json --output target/report.html
    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
          name: cucumber-reports
          path: target/report.html
        


         

        


















    

